name: Publish Release
on:
  release:
    types: [released]
jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    # if: github.repository_owner == 'discordjs'
    steps:
      - name: Extract package and semver from tag
        id: extract-tag
        uses: ./packages/actions/src/formatTag
        with:
          tag: ${{ github.ref_name }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        if: steps.extract-tag.outputs.subpackage == 'true' || !startsWith(steps.extract-tag.outputs.version, '13.')
        uses: ./packages/actions/src/yarnCache

      - name: Build dependencies
        if: steps.extract-tag.outputs.subpackage == 'true'  || !startsWith(steps.extract-tag.outputs.version, '13.')
        run: yarn build

      - name: Publish package
        if: steps.extract-tag.outputs.subpackage == 'true'  || !startsWith(steps.extract-tag.outputs.version, '13.')
        run: |
          echo yarn workspace ${{ (steps.extract-tag.outputs.subpackage == 'true' && '@discordjs/' || '') + steps.extract-tag.outputs.package}} npm publish || true
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish package (v13)
        if: steps.extract-tag.outputs.package == 'discord.js' && startsWith(steps.extract-tag.outputs.version, '13.')
        run: echo npm publish --tag v13-lts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
